package com.privatemediavault.data

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import java.nio.ByteBuffer
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * [KeyStoreProvider] backed by the Android Keystore system.
 *
 * The master key is a 256-bit AES key generated inside the `AndroidKeyStore`
 * provider with GCM/NoPadding. On devices with a trusted execution environment
 * or StrongBox the key material is stored in secure hardware and cannot be
 * extracted by the app or other processes (Requirements 5.1, 5.2).
 *
 * Blob layout produced by [encryptBlob]:
 *
 * ```
 * | 4 bytes: IV length (big-endian int) | IV bytes | ciphertext + 16-byte GCM tag |
 * ```
 *
 * The IV is generated by the Keystore for every encryption (randomized
 * encryption is required for GCM), so identical plaintexts yield distinct
 * blobs.
 */
class AndroidKeyStoreProvider(
    private val keyAlias: String = DEFAULT_KEY_ALIAS,
) : KeyStoreProvider {

    private val keyStore: KeyStore =
        KeyStore.getInstance(ANDROID_KEY_STORE).apply { load(null) }

    override fun getOrCreateMasterKey(): SecretKey {
        (keyStore.getEntry(keyAlias, null) as? KeyStore.SecretKeyEntry)
            ?.let { return it.secretKey }
        return generateMasterKey()
    }

    private fun generateMasterKey(): SecretKey {
        val keyGenerator = KeyGenerator.getInstance(
            KeyProperties.KEY_ALGORITHM_AES,
            ANDROID_KEY_STORE,
        )
        val spec = KeyGenParameterSpec.Builder(
            keyAlias,
            KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
        )
            .setKeySize(KEY_SIZE_BITS)
            .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
            .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
            // GCM requires a unique IV per encryption; let the Keystore pick it.
            .setRandomizedEncryptionRequired(true)
            // No biometric/credential gate: the vault gates access via the PIN.
            .setUserAuthenticationRequired(false)
            .build()
        keyGenerator.init(spec)
        return keyGenerator.generateKey()
    }

    override fun encryptBlob(plaintext: ByteArray): ByteArray {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, getOrCreateMasterKey())
        val iv = cipher.iv
        val ciphertext = cipher.doFinal(plaintext)
        return ByteBuffer.allocate(Int.SIZE_BYTES + iv.size + ciphertext.size)
            .putInt(iv.size)
            .put(iv)
            .put(ciphertext)
            .array()
    }

    override fun decryptBlob(ciphertext: ByteArray): ByteArray {
        require(ciphertext.size >= Int.SIZE_BYTES) { "Blob too short to contain IV length" }
        val buffer = ByteBuffer.wrap(ciphertext)
        val ivLength = buffer.int
        require(ivLength in 1..MAX_IV_LENGTH && ivLength <= buffer.remaining()) {
            "Invalid IV length in blob: $ivLength"
        }
        val iv = ByteArray(ivLength).also { buffer.get(it) }
        val payload = ByteArray(buffer.remaining()).also { buffer.get(it) }

        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(
            Cipher.DECRYPT_MODE,
            getOrCreateMasterKey(),
            GCMParameterSpec(GCM_TAG_LENGTH_BITS, iv),
        )
        return cipher.doFinal(payload)
    }

    private companion object {
        const val ANDROID_KEY_STORE = "AndroidKeyStore"
        const val DEFAULT_KEY_ALIAS = "private_media_vault_master_key"
        const val TRANSFORMATION = "AES/GCM/NoPadding"
        const val KEY_SIZE_BITS = 256
        const val GCM_TAG_LENGTH_BITS = 128
        // Sanity bound; GCM IVs are 12 bytes but allow a little slack.
        const val MAX_IV_LENGTH = 16
    }
}
